---
title: "Drive Time Analysis"
author: "Dusty and JD"
date: "6/20/2019"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Read in and Clean Data

```{r}
library(tidyverse)
library(lubridate)
data = read_csv("drive_times.csv", col_names = FALSE) %>%
  rename(Home=X1,Work=X2,Date=X3,DriveTime=X4) %>% ## Make it easier to read
  filter(substr(Work,1,4)=="6003") %>% ## Place the first four letters of your "Work" Address here
  filter(substr(Home,1,4)=="8109") %>% ## Place the first four letters of your "Home" Address here
  select(-c(X5,X6)) ## Removes these columns for now

cleaned = 
data %>%
  select(-c(Home,Work)) %>% ## temporarily removed for viewing
  mutate(Date = as.POSIXct(Date)) %>% ## must do this to make future comands work
  mutate(DayOfWeek = weekdays(Date)) %>% ## find what day of week 
  filter(DayOfWeek != "Sunday" && DayOfWeek != "Saturday") %>% ## filter out weekends
  mutate(Breaks = round_date(Date, "15 mins")) %>% ## floor to the lowest 15 minutes
  mutate(Breaks = as.POSIXct(cut(Breaks, breaks = "1 hour"))) %>% ## bin 1 hour -- eventually will do 15 mins when I have enought data
  mutate(Breaks = as.factor(format(Breaks, "%H:%M:%S"))) ## extract out just the HMS for plotting purpose and make a factor

cleaned

```

## Histogram by Bin

```{r}
cleaned %>%
  ggplot(aes(x=DriveTime)) +
  geom_histogram() +
  facet_wrap(~Breaks) +
  labs(x="Drive Time", title = "Drive Time Spread by Bin")
```

## Plot of time to see spread

```{r}
cleaned %>%
  ggplot(aes(x=DriveTime,y=0)) +
  geom_point() +
  facet_wrap(~Breaks, ncol = 2,dir = "v")
```

## Summary Statistics

```{r}
cleaned %>%
  count(Breaks)

cleaned %>%
  group_by(Breaks) %>%
  summarise(mean = mean(DriveTime), sd = sd(DriveTime))

```

